import { MD3LightTheme, MD3DarkTheme, configureFonts } from 'react-native-paper';
import type { MD3Theme } from 'react-native-paper';
import { colors, typography } from './index';

const fontConfig = {
    displayLarge: {
        fontFamily: typography.fontFamily.regular,
        fontSize: typography.fontSize.displayLarge,
        fontWeight: typography.fontWeight.regular,
        lineHeight: typography.lineHeight.displayLarge,
        letterSpacing: 0,
    },
    displayMedium: {
        fontFamily: typography.fontFamily.regular,
        fontSize: typography.fontSize.displayMedium,
        fontWeight: typography.fontWeight.regular,
        lineHeight: typography.lineHeight.displayMedium,
        letterSpacing: 0,
    },
    displaySmall: {
        fontFamily: typography.fontFamily.regular,
        fontSize: typography.fontSize.displaySmall,
        fontWeight: typography.fontWeight.regular,
        lineHeight: typography.lineHeight.displaySmall,
        letterSpacing: 0,
    },
    headlineLarge: {
        fontFamily: typography.fontFamily.regular,
        fontSize: typography.fontSize.headlineLarge,
        fontWeight: typography.fontWeight.regular,
        lineHeight: typography.lineHeight.headlineLarge,
        letterSpacing: 0,
    },
    headlineMedium: {
        fontFamily: typography.fontFamily.regular,
        fontSize: typography.fontSize.headlineMedium,
        fontWeight: typography.fontWeight.regular,
        lineHeight: typography.lineHeight.headlineMedium,
        letterSpacing: 0,
    },
    headlineSmall: {
        fontFamily: typography.fontFamily.regular,
        fontSize: typography.fontSize.headlineSmall,
        fontWeight: typography.fontWeight.regular,
        lineHeight: typography.lineHeight.headlineSmall,
        letterSpacing: 0,
    },
    titleLarge: {
        fontFamily: typography.fontFamily.medium,
        fontSize: typography.fontSize.titleLarge,
        fontWeight: typography.fontWeight.medium,
        lineHeight: typography.lineHeight.titleLarge,
        letterSpacing: 0,
    },
    titleMedium: {
        fontFamily: typography.fontFamily.medium,
        fontSize: typography.fontSize.titleMedium,
        fontWeight: typography.fontWeight.medium,
        lineHeight: typography.lineHeight.titleMedium,
        letterSpacing: 0.15,
    },
    titleSmall: {
        fontFamily: typography.fontFamily.medium,
        fontSize: typography.fontSize.titleSmall,
        fontWeight: typography.fontWeight.medium,
        lineHeight: typography.lineHeight.titleSmall,
        letterSpacing: 0.1,
    },
    bodyLarge: {
        fontFamily: typography.fontFamily.regular,
        fontSize: typography.fontSize.bodyLarge,
        fontWeight: typography.fontWeight.regular,
        lineHeight: typography.lineHeight.bodyLarge,
        letterSpacing: 0.15,
    },
    bodyMedium: {
        fontFamily: typography.fontFamily.regular,
        fontSize: typography.fontSize.bodyMedium,
        fontWeight: typography.fontWeight.regular,
        lineHeight: typography.lineHeight.bodyMedium,
        letterSpacing: 0.25,
    },
    bodySmall: {
        fontFamily: typography.fontFamily.regular,
        fontSize: typography.fontSize.bodySmall,
        fontWeight: typography.fontWeight.regular,
        lineHeight: typography.lineHeight.bodySmall,
        letterSpacing: 0.4,
    },
    labelLarge: {
        fontFamily: typography.fontFamily.medium,
        fontSize: typography.fontSize.labelLarge,
        fontWeight: typography.fontWeight.medium,
        lineHeight: typography.lineHeight.labelLarge,
        letterSpacing: 0.1,
    },
    labelMedium: {
        fontFamily: typography.fontFamily.medium,
        fontSize: typography.fontSize.labelMedium,
        fontWeight: typography.fontWeight.medium,
        lineHeight: typography.lineHeight.labelMedium,
        letterSpacing: 0.5,
    },
    labelSmall: {
        fontFamily: typography.fontFamily.medium,
        fontSize: typography.fontSize.labelSmall,
        fontWeight: typography.fontWeight.medium,
        lineHeight: typography.lineHeight.labelSmall,
        letterSpacing: 0.5,
    },
} as const;

// Dark theme for the app
export const paperTheme: MD3Theme = {
    ...MD3DarkTheme,
    colors: {
        ...MD3DarkTheme.colors,
        primary: colors.primary,
        primaryContainer: colors.primaryDark,
        secondary: colors.info,
        secondaryContainer: colors.primarySurface,
        tertiary: colors.success,
        tertiaryContainer: colors.successLight,
        surface: colors.primarySurface,
        surfaceVariant: colors.primaryBackground,
        surfaceDisabled: colors.gray700,
        background: colors.primaryDarker,
        error: colors.error,
        errorContainer: colors.errorLight,
        onPrimary: colors.white,
        onPrimaryContainer: colors.white,
        onSecondary: colors.white,
        onSecondaryContainer: colors.white,
        onTertiary: colors.white,
        onTertiaryContainer: colors.white,
        onSurface: colors.white,
        onSurfaceVariant: colors.gray300,
        onSurfaceDisabled: colors.gray500,
        onBackground: colors.white,
        onError: colors.white,
        onErrorContainer: colors.white,
        outline: colors.gray600,
        outlineVariant: colors.gray700,
        inverseSurface: colors.white,
        inverseOnSurface: colors.primaryDarker,
        inversePrimary: colors.primaryDark,
        elevation: {
            level0: 'transparent',
            level1: colors.primarySurface,
            level2: colors.primaryDark,
            level3: colors.primaryBackground,
            level4: colors.primaryDarker,
            level5: colors.black,
        },
        shadow: colors.black,
        scrim: colors.overlay,
        backdrop: colors.overlayLight,
    },
    fonts: configureFonts({ config: fontConfig }),
    roundness: 8,
};

// TODO: Implement Light theme variant
export const paperLightTheme: MD3Theme = {
    ...MD3LightTheme,
    colors: {
        ...MD3LightTheme.colors,
        primary: colors.primary,
        primaryContainer: colors.primaryLight,
        secondary: colors.info,
        secondaryContainer: colors.gray200,
        tertiary: colors.success,
        tertiaryContainer: colors.successLight,
        surface: colors.white,
        surfaceVariant: colors.gray100,
        surfaceDisabled: colors.gray200,
        background: colors.gray100,
        error: colors.error,
        errorContainer: colors.errorLight,
        onPrimary: colors.white,
        onPrimaryContainer: colors.primaryDarker,
        onSecondary: colors.white,
        onSecondaryContainer: colors.primaryDarker,
        onTertiary: colors.white,
        onTertiaryContainer: colors.primaryDarker,
        onSurface: colors.gray900,
        onSurfaceVariant: colors.gray600,
        onSurfaceDisabled: colors.gray400,
        onBackground: colors.gray900,
        onError: colors.white,
        onErrorContainer: colors.white,
        outline: colors.gray400,
        outlineVariant: colors.gray200,
        inverseSurface: colors.primaryDarker,
        inverseOnSurface: colors.white,
        inversePrimary: colors.primaryLight,
        elevation: {
            level0: 'transparent',
            level1: colors.white,
            level2: colors.gray100,
            level3: colors.gray200,
            level4: colors.gray300,
            level5: colors.gray400,
        },
        shadow: colors.black,
        scrim: colors.overlay,
        backdrop: colors.overlayLight,
    },
    fonts: configureFonts({ config: fontConfig }),
    roundness: 8,
};

export default paperTheme;
